#!/usr/bin/env python3
"""
Module to list all MongoDB databases.
"""

from pymongo import MongoClient


def list_databases():
    """
    Connect to MongoDB and list all databases with their sizes.
    """
    client = MongoClient()
    databases = client.list_database_names()
    for db in databases:
        print(db)


if __name__ == "__main__":
    list_databases()
